version: '3'
services:
  jenkins:
    build: .
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - D:/laboratory/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=""

# No named volumes needed as we're using a local directory path